In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
data = pd.read_csv('2d_sample_run.csv')
data

             x         y      score     class              conv
0     6.859394  2.281548  64.474577  2.1, 2.0           initial
1     8.773102  3.519872  64.474577  8.5, 8.4           initial
2     9.492277  9.160097  64.474577  8.5, 8.4           initial
3     4.265216  7.043726  64.474577  8.5, 8.4           initial
4     1.568081  2.210762  60.957861  2.1, 2.0           initial
...        ...       ...        ...       ...               ...
1024  7.582163  2.360372  70.703129  2.1, 2.0  70.7031290686775
1025  7.435024  2.166412  70.703129  2.1, 2.0  70.7031290686775
1026  7.799034  2.208649  70.703129  2.1, 2.0  70.7031290686775
1027  7.586386  1.804083  70.703129  2.1, 2.0  70.7031290686775
1028  7.550329  2.124944  70.703129  2.1, 2.0  70.7031290686775

[1029 rows x 5 columns]

In [13]:
initial = data.loc[data.conv == 'initial']

In [1]:
classes = list(data['class'])
total_scores = list(data['score'])
print('Total domains of attraction found: ', len(set(classes)))
print('Locations of stable steady states: ', list(set(classes)))

fig, axs = plt.subplots(1, 2, figsize=(10,4))
ax = axs[0]
ax.plot(total_scores)
ax.set_ylabel('Convex Hull Volume', fontsize=15)
ax.set_xlabel('Iterations of BayesOpt', fontsize=15)

ax=axs[1]
sns.scatterplot(data=data, x='x', y='y', hue='class', ax=ax, palette = 'Blues')
# for h in hulls:
#     ax.plot(h.points[h.vertices, 0], h.points[h.vertices, 1], 'r--', lw=2)
ax.set_ylabel(r'$y_{initial}$', fontsize=15)
ax.set_xlabel(r'$x_{initial}$', fontsize=15)

fig.tight_layout()
plt.show()

NameError: name 'data' is not defined